// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_checkfullopen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_checkfullopen));
        
        string IMigrationMetadata.Id
        {
            get { return "201901081852596_Added_checkfullopen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
